### ISSUE TITLE
Any idea why the backup is not running for me?

### ISSUE THREAD

**Issue by myriad007** [bbtsoftware/docker-mssql-backup#58]
I've added the backup to my mssql container but I am having trouble getting the backup to initiate. Here is my docker compose file:

```yaml
version: "3.3"
services:
  server:
    environment:
      - ACCEPT_EULA=Y
      - TZ=America/Toronto
      - MSSQL_SA_PASSWORD=xx%xx&2jLr
      - MSSQL_PID=Express
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
      - shm-size 1g
    ports:
      - 1433:1433
    volumes:
      - /mnt/data/mssql/data:/var/opt/mssql/data
      - /mnt/data/mssql/log:/var/opt/mssql/log
      - /mnt/data/mssql/secrets:/var/opt/mssql/secrets
      - /mnt/data/mssql/backup:/var/opt/mssql/backup
    container_name: sqlpreview
    hostname: sqlpreview
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    user: root
    restart: unless-stopped
  backup:
    image: bbtsoftwareag/mssql-backup
    # for using the cleanup feature, use the backup volume from db.
    volumes:
      - /mnt/data/mssql/backup:/var/opt/mssql/backup
    environment:
      - TZ=America/Toronto
      - DB_SERVER=sqlpreview
      - DB_USER=SA
      - DB_PASSWORD=xx%xx&2jLr
      - DB_NAMES=school2021_1
      - BACKUP_AGE=7
      - BACKUP_CLEANUP=true
      - PACK=tar
      - CRON_SCHEDULE=02 9 27 10 *
    networks:
      - default
networks: {}
```

Have I made an error here?  Here is some terminal output:

> mssql-backup-1  | Starting cron task manager...
mssql-backup-1  |   - Crontab = 02 9 27 10 *
2024-10-27 09:00:25.75 spid49s     [DevOpsSnapshotTelemetryTask] Evaluating the background task.
2024-10-27 09:04:17.15 spid51      XE session 'telemetry_xevents' stopping.
2024-10-27 09:04:17.20 spid51      XE session 'telemetry_xevents' started.

I don't really know how to go about troubleshooting this issue but any advice will be gratefully received.

**Comment by christianbumann** [comment]
Hi @myriad007, quick tipp, in markdown you can format code like yaml more beautiful and readable.
https://stackoverflow.com/questions/75548339/mixing-yaml-and-markdown

Back to your issue

try to remove following

```yaml
    networks:
      - default
networks: {}
```

or add the default network to the sql container too, and add the default network to the nerworks at bottom e.g.
```yaml
version: '3.3'
services:
  server:
    ...
    networks:
      - default
 
  backup:
    ...
    networks:
      - default

networks:
  default:
```

for connecting to the database server, `DB_SERVER=server` (server is the service name)  can be used instead of `DB_SERVER=sqlpreview`
sql preview is an additional dns entry created by `hostname: sqlpreview` which should not be required, but it depends your final docker-compose.yaml and demands
